# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
# message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += code/CCommonTools/CCommonTools.pro \
    code/AddCodeHeader/AddCodeHeader.pro \
    code/WallpaperTool/WallpaperTool.pro \
    code/PixelRuler/PixelRuler.pro \
    code/FileRename/FileRename.pro \
    code/DeveloperTools/DeveloperTools.pro

CONFIG += ordered
