# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += core sql widgets
TEMPLATE = lib
TARGET = CCommonTools

CONFIG(debug, debug|release): {
    DESTDIR = $$PWD/../../bin/debug
}
else {
    DESTDIR = $$PWD/../../bin/release
}
DEFINES += CCOMMONTOOLS_LIB
HEADERS += $$PWD/*.h
SOURCES += $$PWD/*.cpp
RESOURCES += $$PWD/*.qrc
INCLUDEPATH += $$PWD/../../include
